version: "3.7"

services:
  db:
    image: postgres:12.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: GOgraphql
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
