// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Auth struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpInput struct {
	Name            *string `json:"name"`
	Email           string  `json:"email"`
	Password        string  `json:"password"`
	ConfirmPassword string  `json:"confirmPassword"`
}
