// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MeInput struct {
	ID string `json:"id"`
}

type SignUpInput struct {
	Name            *string `json:"name"`
	Email           string  `json:"email"`
	Password        string  `json:"password"`
	ConfirmPassword string  `json:"confirmPassword"`
}
